plugins:
  - jekyll-pwa-plugin
  - github-pages
  - jekyll-seo-tag
  - jemoji
permalink: /:categories/:title/
manifest_name: Catching Fire
manifest_short_name: Catching Fire
manifest_lang: en
manifest_background_color: FFFFFF
manifest_theme_color: FFFFFF
manifest_display: standalone
pwa:
  sw_src_filepath: assets/js/service-worker.js # Optional
  sw_dest_filename: assets/js/service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"
